### ISSUE TITLE
TODO: Bitcart roadmap May 2019

### ISSUE THREAD

**Issue by MrNaif2018** [MrNaif2018/bitcart#28]
- [x] Basic bitcoin features support, core features
- [x] Refine backend gui and make it work without page reload(ajax)
- [x] Finalize CI/CD and deployment
- [ ] Create frontend
- [ ] Add lightning support(electrum/lightning)
- [ ] Add Litecoin support(electrum-ltc)
- [ ] Add omni layer support(electrum-omni probably)

**Comment by MrNaif2018** [comment]
Some of the things are done, frontend is being created right now at github.com/MrNaif2018/bitcart-frontend. As it is the end of May and start of June this issue will be closed and a new one will be opened.

**Comment by MrNaif2018** [comment]
#34 is open, this roadmap is closed.
