### ISSUE TITLE
TODO: Bitcart roadmap June 2019

### ISSUE THREAD

**Issue by MrNaif2018** [MrNaif2018/bitcart#34]
- [x] Create frontend
- [ ] Add lightning support(electrum/lightning)
- [ ] Add Litecoin support(electrum-ltc)
- [ ] Add omni layer support(electrum-omni probably)
Main target for this month is to try to create frontend.
Previous month: #28

**Comment by MrNaif2018** [comment]
Frontend is created, now it's time to add checkout. Moving to new month. #39
