### ISSUE TITLE
TODO: Bitcart roadmap July 2019

### ISSUE THREAD

**Issue by MrNaif2018** [MrNaif2018/bitcart#39]
- [x] Fully connect frontend and backend(add checkout)
- [ ] Add lightning to UI
- [ ] Refactor code
- [ ] Investigate about core api, undo commit 5b2c63c1ba4937262b0866ef6ae7e5dd5ac4993c in some time
- [ ] Unify docker install, make it all work flawlessly
- [x] Add lightning support(electrum/lightning)
- [ ] Add Litecoin support(electrum-ltc)
- [ ] Add omni layer support(electrum-omni probably)
Main target for this month is to try to create frontend.
[Frontend](https://github.com/MrNaif2018/bitcart-frontend) created 
Lightning created #51 
New target: add lightning to UI
Previous month: #34

**Comment by MrNaif2018** [comment]
Good job for this month, lightning added, docker install improved, all is going good. Time for the next month! New roadmap is #61
