### ISSUE TITLE
TODO: Bitcart roadmap August 2019

### ISSUE THREAD

**Issue by MrNaif2018** [MrNaif2018/bitcart#61]
- [ ] Switch to fastapi (api done, 90% test coverage, almost done tests)
- [ ] Create admin panel(backend section) working with fastapi api
- [ ] Refactor daemons, as for now every other daemon is almost a copy of BTC daemon
- [ ] Improve docs
- [ ] Improve checkout design
- [ ] Add more examples of usage
- [ ] Add Litecoin support(electrum-ltc)
- [ ] Add omni layer support(electrum-omni probably)
Previous month: #39

**Comment by MrNaif2018** [comment]
The month is over, next month is here #66 
Fastapi api was created, SDK recieved a few bug fixes and new features.
