### ISSUE TITLE
TODO: Bitcart roadmap September 2019

### ISSUE THREAD

**Issue by MrNaif2018** [MrNaif2018/bitcart#66]
- [x] Finish fastapi testing
- [ ] Create admin panel(backend section) working with fastapi api (MrNaif2018/bitcart-admin#1)
- [x] Refactor daemons, as for now every other daemon is almost a copy of BTC daemon
- [ ] Improve docs (MrNaif2018/bitcart-docs#3)
- [ ] Improve checkout design (MrNaif2018/bitcart-frontend#38)
- [ ] Add more examples of usage and new features to SDK(MrNaif2018/bitcart-sdk#3)
- [ ] Tor and using your own node support(MrNaif2018/bitcart-docker#8)
- [x] Add Litecoin support(electrum-ltc)
- [x] Add gzro support(electrum-gzro)
- [ ] Add omni layer support(electrum-omni probably)
Previous month: #61

**Comment by MrNaif2018** [comment]
This roadmap will link to possible things to add or fix.
Current hacktoberfest issues: MrNaif2018/bitcart-docs#3, #71 .
Help is welcome

**Comment by MrNaif2018** [comment]
The September is over! Hacktober is coming!
Hacktober roadmap is #74 
Results for this month:
Fastapi api was finalized and tested well. The only missing tests are websocket ones #71 
Daemons were refactored a lot, now it is very easy to add new altcoin.
Two altcoins were added to bitcart as example, ltc and gzro.
We hope to do a lot next month!
