### ISSUE TITLE
TODO: Bitcart roadmap Hacktober 2019

### ISSUE THREAD

**Issue by MrNaif2018** [MrNaif2018/bitcart#74]
This month [Hacktoberfest](https://hacktoberfest.digitalocean.com/) is held!
We welcome all new contributors, this issue is a list of all issues from bitcart projects(new features, bug fixes, etc.).
If you have any questions regarding the project, open an issue on github or contact us in our [Telegram group](https://t.me/bitcartcc).
Main hacktoberfest discussion can be done in this related issue (#72)
- [x] Create admin panel(backend section) working with fastapi api (MrNaif2018/bitcart-admin#1)
- [ ] Improve docs (MrNaif2018/bitcart-docs#3)
- [ ] Improve checkout design (MrNaif2018/bitcart-frontend#38)
- [ ] Add more examples of usage and new features to SDK(MrNaif2018/bitcart-sdk#3)
- [ ] Tor and using your own node support(MrNaif2018/bitcart-docker#8)
- [ ] Add omni layer support(electrum-omni probably)
Previous month: #66

**Comment by MrNaif2018** [comment]
This roadmap will link to possible things to add or fix.
Current hacktoberfest issues: MrNaif2018/bitcart-docs#3, #71, MrNaif2018/bitcart-admin#1, MrNaif2018/bitcart-frontend#38, MrNaif2018/bitcart-docker#8, MrNaif2018/bitcart-sdk#3
Help is welcome

**Comment by MrNaif2018** [comment]
This month we have improved bitcart merchants API a lot, created amazing admin panel and bitcart site!
We've added alembic migrations and improved our test suite! Thanks to all our contributors!
Next month: #84
