### ISSUE TITLE
TODO: Bitcart roadmap November 2019

### ISSUE THREAD

**Issue by MrNaif2018** [MrNaif2018/bitcart#84]
- [x] Improve admin panel, add auth and admin actions(for server admins) (MrNaif2018/bitcart-admin#1)
- [x] Add authentification to bitcart merchants API (#76)
- [ ] Improve docs (MrNaif2018/bitcart-docs#3)
- [ ] Improve checkout design (MrNaif2018/bitcart-frontend#38)
- [ ] Add more examples of usage and new features to SDK(MrNaif2018/bitcart-sdk#3)
- [ ] Tor and using your own node support(MrNaif2018/bitcart-docker#8)
- [ ] Add omni layer support(electrum-omni probably)
Previous month: #74

**Comment by MrNaif2018** [comment]
This month we added the long-awaited auth to admin panel and APIs, which made bitcart ready to use for your stores. Many admin panel improvements, including autocompletes, input validation and user management was added.
Last month of 2019!
Next month: #92
