### ISSUE TITLE
TODO: Bitcart roadmap January 2020

### ISSUE THREAD

**Issue by MrNaif2018** [MrNaif2018/bitcart#96]
Second year of BitcartCC development!
Massive update from 2019 coming out 1 January 2020 at 20:20!
- [x] Add server management settings to admin (almost done)
- [x] Improve docs (almost done)
- [x] Improve checkout design (MrNaif2018/bitcart-frontend#38)
- [ ] Add more examples of usage and new features to SDK(MrNaif2018/bitcart-sdk#3)
- [ ] Tor and using your own node support(MrNaif2018/bitcart-docker#8)
- [ ] Add omni layer support(electrum-omni probably)
Previous month: #92

**Comment by MrNaif2018** [comment]
This month we have done a lot of progress, brand new docs, improved checkout, improved admin panel. 
Next month: #98
