### ISSUE TITLE
TODO: Bitcart roadmap February 2020

### ISSUE THREAD

**Issue by MrNaif2018** [MrNaif2018/bitcart#98]
- [ ] Add more server management settings to admin (lightning management?)
- [ ] Finalize docs
- [ ] Add more examples of usage and new features to SDK(MrNaif2018/bitcart-sdk#3)
- [ ] Tor and using your own node support(MrNaif2018/bitcart-docker#8)
- [ ] Add omni layer support(electrum-omni probably)
Previous month: #96

**Comment by MrNaif2018** [comment]
A massive update came out, we have switched our auth scheme to OAuth tokens.
Next month(skipping March due to some issues): #103
